baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-book"

#[params]
#    BookMenuBundle = '/menu'

#[markup]
#  [markup.goldmark]
#    [markup.goldmark.parser]
#      [markup.goldmark.parser.attribute]
#        block = true
#        title = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
